spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: DigitalAccounts
  flyway:
    locations: classpath:scripts/db

server:
  servlet:
    context-path: /digital-accounts/api
  port: 8080

